---
# Harbor access settings
harbor_tls_enabled: true
harbor_tls_cert_source: auto
harbor_https_node_port: 30100
harbor_external_url_scheme: https
harbor_external_url_port: "{{ harbor_https_node_port }}"
